//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DS.HeartSummer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentGrade
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string UserId { get; set; }
        public string Term { get; set; }
        public string Course { get; set; }
        public string Credit { get; set; }
        public string CourseType { get; set; }
        public string Quality { get; set; }
        public string CheckMode { get; set; }
        public string PrimiGrade { get; set; }
        public string ValidGrade { get; set; }
        public string Mark { get; set; }
        public string UserPwd { get; set; }
    }
}
