//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DS.HeartSummer.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SummerModelContainer : DbContext
    {
        public SummerModelContainer()
            : base("name=SummerModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Users> Users { get; set; }
        public DbSet<Settings> Settings { get; set; }
        public DbSet<Timeline> Timeline { get; set; }
        public DbSet<FontAwesome> FontAwesome { get; set; }
        public DbSet<StudentGrade> StudentGrade { get; set; }
        public DbSet<Terms> Terms { get; set; }
        public DbSet<Defineds> Defineds { get; set; }
        public DbSet<StudentGrades> StudentGrades { get; set; }
        public DbSet<StudentImageTable> StudentImageTable { get; set; }
        public DbSet<StudentInfo> StudentInfo { get; set; }
    }
}
